# Generated by Django 5.2.6 on 2025-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('area', models.FloatField(help_text='Area in km²')),
                ('number_of_schools', models.PositiveIntegerField(default=0)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('number_of_teachers', models.PositiveIntegerField(default=0)),
                ('literacy_rate', models.FloatField(help_text='Literacy rate in %')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
    ]
