# Generated by Django 5.2.6 on 2025-09-21 10:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wereda'),
    ]

    operations = [
        migrations.AddField(
            model_name='wereda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 21, 3, 43, 17, 70924)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wereda',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weredas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wereda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
