# Generated by Django 5.2.6 on 2025-09-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wereda_created_at_wereda_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wereda',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'wereda_office'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_weredas', to=settings.AUTH_USER_MODEL),
        ),
    ]
