# Generated by Django 5.2.6 on 2025-09-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wereda_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Preparatory', 'Preparatory'), ('Combined', 'Combined')], max_length=20)),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('NGO', 'NGO'), ('Religious', 'Religious')], max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('teacher_count', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principal', models.CharField(blank=True, max_length=100)),
                ('established', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'school'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schools', to=settings.AUTH_USER_MODEL)),
                ('wereda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wereda')),
            ],
        ),
    ]
