# Generated by Django 5.2.6 on 2025-09-22 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'senate'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervise_schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
